repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.4.0
  hooks:
   - id: mypy
     exclude: |
       (?x)^(
           tests/samples/.*|
           integration_tests/.*
       )$
     additional_dependencies:
       [
         "types-mock==5.0.*",
    ]
