name: Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    strategy:
      matrix:
        python-version: ['3.9', '3.10',  '3.11' ]
    steps:
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install -r requirements/test.txt
      - name: Run pytest
        env:
          COVERAGE_FILE: coverage/py${{ matrix.python-version }}-coverage
        run: coverage run --source=codemodder/ -m pytest -v
      - name: Report coverage
        env:
          COVERAGE_FILE: coverage/py${{ matrix.python-version }}-coverage
        run: coverage report -m --fail-under=96
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          name: py${{ matrix.python-version }}-coverage
          path: ./coverage/py${{ matrix.python-version }}-coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
